# Generated by Django 3.1.3 on 2020-11-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastEdited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
